# Generated by Django 4.1.4 on 2022-12-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_delete_blog_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_preview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
