# Generated by Django 4.1.4 on 2022-12-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_blog_preview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog_preview',
        ),
    ]
